services:
  - docker
  
script:
- docker build -t dantebarba/voucher-unlp-bot:latest .
- docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
- docker push dantebarba/voucher-unlp-bot:latest
